### ISSUE TITLE
Problem with autoswitch

### ISSUE THREAD

**Issue by pattonthompson** [rattboi/extron-scart-adapter#9]
I’ve tried two different extrons.  84 series and 300 series.  Everything works perfectly manually switching, 8 consoles in, 1 output.  All scart.  I’ve flashed the custom boot.py to the root of the esp32.  Autoswitching is not working.  Have tried factory resetting both extrons.  Is there a step I’m missing?  Any help greatly appreciated.

**Comment by rattboi** [comment]
https://github.com/rattboi/extron-scart-adapter/tree/master/esp32-switcher#code 

I know these steps are wishy-washy. Just gotta verify you did in fact follow these steps and have micropython installed onto your esp32 and running this code.

**Comment by pattonthompson** [comment]
I appreciate your reply.  the soldering part wasn't bad but I'm new to micropython.  I think this confirms I have the code in the right spot on the ESP32 but I could be wrong.  See attached screenshot.
![bootpy](https://user-images.githubusercontent.com/54949217/129829055-347311d7-dda8-4964-a771-94b83d2f21ab.png)

**Comment by rattboi** [comment]
Indeed, I would agree that you have micropython and the code loaded up.

Further debugging ideas:

1. take one of the JST 2-pin cables that would go to the auto-switcher and cut and wire to multimeter. Plug into the Scart Input adapter card. Make sure you see a signal change when you turn the console on and off from the adapter card.

2. Do direct connection from your PC to the extron using a regular USB->RS232 adapter. Configure for 9600 baud, 8 data bits, no parity bit, 1 stop bit. You should be able to switch channels by typing `1*1!`, `2*2!`, `1*2!`. The format is `<input>*<output>!`

3. Get some pictures of your setup and attach them and I'll see if I see anything odd.

4. Message me on discord at rattboi#7637, and I can try and work together with you on other ideas.

**Comment by pattonthompson** [comment]
Thanks again for the detailed reply.  

I’m only getting 0.1 volts whether the console is powered on or off.  Doesn’t matter if I measure on the jst cables or directly on the pins on the connector cards.  This is WITHOUT the autoswitcher plugged in.  That seems like a problem.

My setup is an Extron 300 series.  8 consoles nes, snes, n64, genesis, saturn, neo geo cd, pc engine, ps1.  All rgb modded by myself or native rgb.  All the cables are high quality from retro access or retrogamingcables.  They are all wired for properly attenuated C-sync, or have a sync stripper in the cable.  The 1 output I use on the extron goes to a shinybow scart to component transcoder, hd retrovision male-male component cables to Sony KV32FS100.

I think the soldering is ok, I’m no Voultar just a hobbyist but I did manage to mod those consoles myself. 

Happy to send pictures of something specific if that helps or I could retest the voltage with the autoswitcher board plugged in the rs232.

Again thanks for the help!  Even if I dont get the autoswitch working its still an awesome setup!  Manual is still good.

**Comment by rattboi** [comment]
Removed from the extron input board (just cable + system), check the DC voltage between SCART pin 8 and shield/pin 21. It should be 5+ volts with the system on.

Check a few systems.

This will determine if it's something on the extron scart input board or something with the cables.

**Comment by pattonthompson** [comment]
Sure enough got 5 volts on the scart cables.  I think I probably reversed the polarity of the diodes.  If that is correct it should be an easy fix.  Attached a close up of one of my input cards (I did them all the same way).

![4F22687F-D008-4D4D-AC7B-436848206FA4](https://user-images.githubusercontent.com/54949217/131602032-5b49e607-5562-4825-abd5-b36f758a973c.jpeg)

**Comment by rattboi** [comment]
Components look like they're oriented correctly, but the soldering needs some work. I shouldn't be able to see the hole in R2 or D2, and I'd say R3 looks like a cold solder joint. I'd take another pass with each, and use some flux if you have some. 

Then I'd take the input card, attach a console SCART, and check the voltage from point to point along the path. From ground to the right-hand side of D1 should by 5V. IIRC, it should be like 4.3V from ground to the left-hand side of D1. The goal is to have something ~3V or more at the 2-pin connector on the top of the input board.

**Comment by rattboi** [comment]
Looking over this again, I see that the main mistake is mine. You have a 100k resistor in R2, and that's correct according to the BOM I have in the readme. Unfortunately, that was a mistake and it should be 100 ohms, not 100k ohms. I'll be fixing up the BOM today. The resistor code should be BROWN BLACK BROWN GOLD, for 100 ohms.

**Comment by rattboi** [comment]
Fixed in the BOM. Really sorry about that.

Closing issue. Feel free to re-open if you have more problems.

**Comment by pattonthompson** [comment]
Sounds good thank you.  I did confirm with my multimeter.  Ordered the 100
ohm resistors.  Awesome of you to provide such good support.

Patton

**Comment by pattonthompson** [comment]
Its been awhile but i came back to this.  Still having the same problem:  manual switching is perfect, autoswitch not working.  I replaced R2 for 100 ohm resistors on all the input cards.  Im getting ~2.75V on the input sensing JST wires.  Maybe this is not enough?  You mentioned it should be 3 volts or more?

I reflashed the esp 32 and replaced boot.py just to be sure and had same result as above - code seems to be executing.

I hooked up the extron to PC.  I have no idea how to input those commands you suggested.  I.e. trying to use a program in windows to communicate ascii commands, etc.   But I did find the extron software and that works in creating ties, etc.  I was able to change to 9600 baud.  I wasn’t able to definitively check or change 8 data bits, no parity bit, 1 stop bit.  That feature wasn’t in the very basic software I could find.  Those are allegedly the factory setting and I have done several factory resets on the extron.  I forget what the exact setting is called but i have the extron set to “lock mode 1”, so front panel inputs / changes are not possible but theoretically should still be able to make changes through rs232 (kids what can i say🤣).  

I dont know if this means anything but with the ttl rs232 connector unplugged, console 1 powered on and manually outputting to output one I get a little over 5V on the TxD pin compared to ground.  Using a standard iphone 5 volt charger to power esp32 board.

At this point I have no idea what I’m missing.  I feel like it could be something very dumb like a particular firmware for extron or esp 32.  Some Extron setting I’m missing.  Could be the 8 data bits, no parity bit, 1 stop bit issue.  Maybe my scart cables are not allowing enough voltage to get to board in the first place and thats why I get ~2.7 vots on the jst wires.  A lower resistor at R2 perhaps?  Do you wait to plug in the esp32 unti AFTER the extron is on?  I looked at some pics you had of the assembled switcher board on twitter everything appears to be the correct orientation.

As you can see I’m lost 🤷‍♂️.  The soldering / hardware stuff I understand more than the programming.  Any further help troubleshooting would be appreciated and might help someone else who’s stuck like me.
